---
title: "Activity: Nuclear Reactors"
author: "YOUR NAME HERE"
output: html_notebook
---

```{r}
library(tidyverse)

```

## Scrape the Data 

```{r}

library(rvest)


url <- "https://en.wikipedia.org/wiki/List_of_commercial_nuclear_reactors"
page <- read_html(url)
table <- html_nodes(page, "table.wikitable.sortable")
japan_rows <- html_nodes(table, "tbody tr")[-1]  
japan_reactors_data <- lapply(japan_rows, function(row) {
  reactor_name <- html_text(html_nodes(row, "td")[1])
  reactor_type <- html_text(html_nodes(row, "td")[3])
  reactor_capacity <- html_text(html_nodes(row, "td")[4])
  data.frame(Reactor_Name = reactor_name, Reactor_Type = reactor_type, Reactor_Capacity = reactor_capacity)
})

japan_reactors_data <- do.call(rbind, japan_reactors_data)

print(japan_reactors_data)


```


## Your turn: In what ways is the table tidy? How is it not tidy? What’s different about it from a tidy table?

the wekipidia table page is not tidy and requires some transformations to make it tidy.



## Your Turn: Plot Net Generation Capacity vs Construction Date

```{r}
library(tidyverse)
library(rvest)

# Scrape the data for Japan Reactors
url <- "https://en.wikipedia.org/wiki/List_of_commercial_nuclear_reactors"
page <- read_html(url)
table <- html_nodes(page, "table.wikitable.sortable")
japan_rows <- html_nodes(table, "tbody tr")[-1]

japan_reactors_data <- lapply(japan_rows, function(row) {
  reactor_name <- html_text(html_nodes(row, "td")[1])
  reactor_type <- html_text(html_nodes(row, "td")[3])
  reactor_capacity <- html_text(html_nodes(row, "td")[4])
  construction_date <- html_text(html_nodes(row, "td")[6])
  
  data.frame(
    Reactor_Name = reactor_name,
    Reactor_Type = reactor_type,
    Reactor_Capacity = reactor_capacity,
    Construction_Date = construction_date
  )
})

japan_reactors_data <- do.call(rbind, japan_reactors_data)


```



## Your Turn: Reconstruct Info Graphic of Japan Reactors (or other country of interest)

```{r}




plot <- ggplot(reactor_count, aes(x = Reactor_Type, y = 0, xend = Reactor_Type, yend = Count)) +
  geom_segment(color = "skyblue", linewidth = 10) +
  labs(x = "Reactor Type", y = "Count", title = "Japan Reactors - Number of Reactors by Type") +
  theme_minimal()


print(plot)




```